Fix PHP 7.3.7 compatibility
Fixes an PHP 7.3.7 compatibility issue due to an invalid escape sequence.

Example:

preg_split(): Compilation failed: escape sequence is invalid in character class at offset 10

geo-parser/vendor/doctrine/lexer/lib/Doctrine/Common/Lexer/AbstractLexer.php:259
geo-parser/vendor/doctrine/lexer/lib/Doctrine/Common/Lexer/AbstractLexer.php:96
geo-parser/lib/CrEOF/Geo/String/Parser.php:91
geo-parser/tests/CrEOF/Geo/String/Tests/ParserTest.php:78